[package]
name = "raft-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"
log = "0.4.20"

[build-dependencies]
tonic-build = "0.9"
